### PR TITLE
expand chart functionality

### PR DESCRIPTION
**Pull request by Amos-85**
Expand cloud custodian helm chart functionality to support:

- Persistence Volume / Existing Persistence volume claim.
- Customize args.
- Ability to use external secret instead of envars as secrets.
- Upgrade image version to 9.11.0.
- Add CronJob restartPolicy.

### CODE REVIEW

**Comment by Amos-85** [comment]
@kapilt Is the project currently open for contribution ?

**Comment by kapilt** [comment]
definitely, my apologies, i haven't been monitoring this repo for issues/prs as actively.

**Review by wwitzel3 — CHANGES_REQUESTED** [review]
This is looking good, the version and badge info in the README got missed with the version updates.

**Comment by wwitzel3** [comment]
Was able to successfully upgrade from 0.1 to 0.2 and my job still ran after. I did not manually test all of the new configuration values but none of them fail `helm lint`

```
❯ helm history cloud-custodian-cron-1617375399
REVISION        UPDATED                         STATUS          CHART                           APP VERSION     DESCRIPTION
1               Fri Apr  2 10:56:39 2021        superseded      cloud-custodian-cron-0.1.0      0.9.9           Install complete
2               Fri Apr  2 11:06:24 2021        deployed        cloud-custodian-cron-0.2.0      0.9.11.0        Upgrade complete
```

**Comment by Amos-85** [comment]
@kapilt / @wwitzel3 ,

Thanks for commit review.
Let me know if you think about modifying some commit changes before merge.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
