### PR TITLE
switch to c7n image instead of c7n-kube

### PR DESCRIPTION
**Pull request by sontek**

### CODE REVIEW

**Comment by thisisshi** [comment]
doesn't this need to use a different entrypoint as well? c7n-kates?

**Comment by sontek** [comment]
@thisisshi No, its using that already in the `controller.yml`: 

https://github.com/cloud-custodian/helm-charts/blob/af9eaa2ff0d7f3646f8c0b68f4cb855b43ca093a/charts/c7n-kube/templates/controller.yaml#L30

**Review by kapilt — APPROVED** [review]
Lgtm

**Comment by kapilt** [comment]
fwiw, let's please put in a description on prs re why... afaicr the original reason to have c7n-kube image was to avoid some of the larger sdks that are not material for the k8s use cases which should change image size from 1gb, to ~250-300mb

**Pull request merged**
